name: deploy
run-name: Deploying to DreamHost

on:
  workflow_dispatch:
  push:
    branches:
      - master

concurrency:
  group: "${{ github.workflow }} @ ${{ github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  deploy-to-dreamhost:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: npm

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Install zip
        uses: montudor/action-zip@v1

      - name: Zip files
        run: zip -qq -r ../dist_aaronmandseth.com.zip ./*
        working-directory: dist

      - name: Upload to webserver
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.DEPLOY_IP }}
          port: 22
          sftp_only: true
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          local_path: "./dist_aaronmandseth.com.zip"
          remote_path: ${{ secrets.DEPLOY_TEMP_PATH }}

      - name: Deploy on webserver
        uses: appleboy/ssh-action@v0.1.10
        env:
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
          DEPLOY_TEMP_PATH: ${{ secrets.DEPLOY_TEMP_PATH }}
        with:
          host: ${{ secrets.DEPLOY_IP }}
          port: 22
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          envs: DEPLOY_PATH,DEPLOY_TEMP_PATH
          script_stop: true
          script: |
            touch "$DEPLOY_PATH/.offline"
            rm -r "$DEPLOY_PATH/_astro" "$DEPLOY_PATH/images"
            rm "$DEPLOY_PATH/favicon.ico" "$DEPLOY_PATH/index.html"
            unzip -qq "$DEPLOY_TEMP_PATH/dist_aaronmandseth.com.zip" -d "$DEPLOY_PATH"
            rm "$DEPLOY_TEMP_PATH/dist_aaronmandseth.com.zip"
            rm "$DEPLOY_PATH/.offline"
